<script lang="ts">
	/* eslint-disable svelte/no-navigation-without-resolve --
	 * Static internal links to the sibling legal pages; resolve() adds noise. */
	import { company, LEGAL_UPDATED } from '$lib/legal';
</script>

<svelte:head>
	<title>Terms of Service — {company.product}</title>
	<meta name="robots" content="noindex" />
</svelte:head>

<h1>Terms of Service</h1>
<p class="updated">The agreement between you and {company.name} for using {company.product}.</p>

<h2>1. The service</h2>
<p>
	{company.product} is a post-game chess review tool operated by {company.name}. It imports your
	games from chess.com and Lichess, analyses them with a chess engine, and offers plain-English
	explanations of your moves. By using {company.product} you agree to these terms.
</p>

<h2>2. Eligibility and your account</h2>
<p>
	You must be able to enter into a binding contract to use the service. We sign you in with a magic
	link sent to your email — keep access to that inbox secure, as anyone with it can access your
	account. You are responsible for activity under your account.
</p>

<h2>3. Acceptable use</h2>
<p>You agree not to:</p>
<ul>
	<li>use the service for any unlawful purpose;</li>
	<li>
		scrape, overload, or attempt to disrupt the service or the language model behind the coach;
	</li>
	<li>attempt to access accounts or data that are not yours;</li>
	<li>resell or redistribute the service without our permission.</li>
</ul>

<h2>4. Third-party platforms</h2>
<p>
	When you connect a chess.com or Lichess username, you confirm you are entitled to access that data,
	and your use of those platforms remains subject to their own terms. We are not affiliated with
	chess.com or Lichess.
</p>

<h2>5. The coach is guidance, not gospel</h2>
<p>
	Move explanations are generated by a language model from engine analysis. They are intended to
	help you learn and may be incomplete or wrong. They are not professional advice, and you use them
	at your own discretion.
</p>

<h2>6. Availability and changes</h2>
<p>
	The service is provided "as is" and "as available". We may change, suspend, or discontinue
	features, and we do not guarantee uninterrupted availability. We may update these terms; continued
	use after a change means you accept the updated terms.
</p>

<h2>7. Liability</h2>
<p>
	To the extent permitted by law, {company.name} is not liable for indirect or consequential damages
	arising from your use of the service. Nothing in these terms limits liability that cannot be
	limited under German law, including for injury to life, body or health, or for intent and gross
	negligence.
</p>

<h2>8. Ending your use</h2>
<p>
	You can stop using {company.product} and request deletion of your account and data at any time by
	emailing <a href="mailto:{company.email}">{company.email}</a>. We may suspend or terminate access
	if you breach these terms.
</p>

<h2>9. Governing law</h2>
<p>
	These terms are governed by the law of the Federal Republic of Germany. Where permitted, the place
	of jurisdiction is Ulm, Germany.
</p>

<h2>10. Contact</h2>
<p>
	Questions about these terms: <a href="mailto:{company.email}">{company.email}</a>. See also our
	<a href="/impressum">Imprint</a> and <a href="/privacy">Privacy Policy</a>.
</p>

<p class="updated">Last updated: {LEGAL_UPDATED}</p>
